[METADATA]

modified = 2023-05-22T00:00:00.000Z

expires = 2050-05-01T00:00:00.000Z



[[ACCOUNTS]]

address = "rw7KX9bFy5EqFXC9hz7Ukg2YoGSV4HVRib"

desc = "AGylds Ranch. Fungible base, counter cryptocurrency"


[[SERVERS]]

json_rpc = "https://s1.ripple.com:51234/"

ws = "wss://s1.ripple.com/"

peer = "https://s1.ripple.com:51235/"

desc = "General purpose server cluster"

[[SERVERS]]

json_rpc = "https://s2.ripple.com:51234/"

ws = "wss://s2.ripple.com/"

peer = "https://s2.ripple.com:51235/"

desc = "Full-history server cluster"

[[SERVERS]]

json_rpc = "https://s.testnet.rippletest.net:51234/"

ws = "wss://s.testnet.rippletest.net:51233/"

peer = "https://s.testnet.rippletest.net:51235/"

network = "testnet"

desc = "Test Net public server cluster"

[[PRINCIPALS]]

name = "AGylds Ranch"

email = "frolic_obelisk_0s@icloud.com" # Not my real email address

[[CURRENCIES]]

code = "AGY"

issuer = "rw7KX9bFy5EqFXC9hz7Ukg2YoGSV4HVRib"

network = "mainnet"

display_decimals = 4

symbol = "AGY"
